FROM ubuntu:latest

RUN apt update
RUN apt install python3
RUN apt install python3-pip
RUN apt install git-core
RUN python -m pip install

RUN git clone https://github.com/cloudmesh-community/sp19-222-101.git

WORKDIR /sp19-222-101

